import random

MADATORY_POSITION = [ 'SitRelax', 'Sit', 'WipeForehead', 'Stand', 'Hello', 'StandZero', 'Crouch']

COMPATIBILITIES = {
        "StandInit": ["StandZero", "Stand", "Crouch", "Sit", "SitRelax", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "StandZero": ["StandInit", "Stand", "Crouch", "Sit", "SitRelax", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "Stand": ["StandInit", "StandZero", "Crouch", "Sit", "SitRelax", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "Crouch": ["StandInit", "StandZero", "Stand", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "Sit": ["StandInit", "StandZero", "Stand", "Crouch", "WipeForehead", "Guitar", "DiagonalRight", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "SitRelax": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "Guitar", "DiagonalRight", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight"],
        "WipeForehead": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "Guitar": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "DiagonalRight": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "RotationRightFoot": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "RotationLeftFoot": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "RotationHandgunObject": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "RotationRightArm": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "DoubleMovement": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "ArmsOpening": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "UnionArms": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "MoveForward": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "MoveBackward": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "DiagonalLeft": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "HappyBirthday": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "Workout", "SprinklerLeft", "SprinklerRight", "Hello"],
        "Workout": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "SprinklerLeft", "SprinklerRight", "Hello"],
        "SprinklerLeft": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerRight", "Hello"],
        "SprinklerRight": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "Hello"],
        "Hello": ["StandInit", "StandZero", "Stand", "Crouch", "Sit", "WipeForehead", "Guitar", "DiagonalRight", "RotationRightFoot", "RotationLeftFoot", "RotationHandgunObject", "RotationRightArm", "DoubleMovement", "ArmsOpening", "UnionArms", "MoveForward", "MoveBackward", "DiagonalLeft", "HappyBirthday", "Workout", "SprinklerLeft", "SprinklerRight"],
    }

ALL_POSES = COMPATIBILITIES.keys()

MIN = 7

def randcompatibilities(compatibilities = COMPATIBILITIES):

    comp_list = list(compatibilities.items())
    for item in comp_list:
        random.shuffle(item[1])
    random.shuffle(comp_list)
    compatibilities = dict(comp_list)

    return compatibilities
